apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: github-authn
  name: github-authn
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: github-authn
  template:
    metadata:
      labels:
        k8s-app: github-authn
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - image: oursky/kubernetes-github-authn
        name: kubernetes-github-authn
        ports:
        - containerPort: 3000
          hostPort: 3000
          protocol: TCP
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
